name: balancer
services:
  #################################################################################################
  #                                              API                                              #
  #################################################################################################
  api:
    build: ../api
    image: jesusgraterol/balancer-api:latest
    ports:
      - 5075:5075
    environment:
      NODE_ENV: "development"
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "10"
        compress: "true"



  #################################################################################################
  #                                              GUI                                              #
  #################################################################################################
  gui:
    build:
      context: ../gui
      args:
        NODE_ENV: "development"
    image: jesusgraterol/balancer-gui:latest
    ports:
      - 8090:8090
    environment:
      NODE_ENV: "development"
    depends_on:
      - api
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "10"
        compress: "true"
  