name: balancer

###################################################################################################
#                                             SERVICES                                            #
###################################################################################################
services:

  #################################################################################################
  #                                              API                                              #
  #################################################################################################
  api:
    container_name: balancer-api
    build: ../api
    image: jesusgraterol/balancer-api:latest
    ports:
      - 5075:5075
    environment:
      NODE_ENV: "development"
      testMode: "true"
      restoreMode: "false"
      serverPort: "5075"
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "10"
        compress: "true"





  #################################################################################################
  #                                              GUI                                              #
  #################################################################################################
  gui:
    container_name: balancer-gui
    build:
      context: ../gui
      args:
        NODE_ENV: "development"
    image: jesusgraterol/balancer-gui:latest
    ports:
      - 8090:8090
    environment:
      NODE_ENV: "development"
    depends_on:
      - api
    logging:
      driver: local
      options:
        max-size: 10m
        max-file: "10"
        compress: "true"
  




###################################################################################################
#                                             VOLUMES                                             #
###################################################################################################
volumes:
    pgdata:
    pgdata-management: